[project]
name = "fact-check-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firecrawl-py>=3.3.2",
    "google-adk>=1.12.0",
    "markitdown[all]>=0.1.2",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
